---
# Start with Installing the required packages on the Host

- name: Install Basic Required Packages.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - "{{ basic_packages }}"

# Once Packages are installed, lets start the Libvirt Service
- name: Start Libvirtd Service
  systemd:
    state: started
    name: libvirtd
    enabled: yes


- name: Check the SSH KeyPair Existence
  stat:
    path: "~/.ssh/lab_rsa"
  register: ssh_key_status
  tags:
    - ssh

- name: Debug
  debug:
    msg: "{{ ssh_key_status.stat.exists }}"
  tags:
    - ssh


- name: Create SSH Key if not existing
  shell: |
    ssh-keygen -b 2048 -t rsa -f ~/.ssh/lab_rsa -q -N ""  
# when: ssh_key_status.stat.exists == 'false'
  ignore_errors: yes
  tags:
    - ssh

# Enable Nested KVM
- name: Enable Nested KVM
  copy:
    dest: /etc/modprobe.d/kvm-nested.conf
    content: |
      options kvm-intel nested=1


# Prepare the KVM Image 
- name: Remove Cloud-Init & Add Password  
  shell: | 
    export LIBGUESTFS_BACKEND=direct && virt-customize -a "{{ role_path }}/files/{{ rhel9_kvm_image }}" --root-password password:redhat --ssh-inject "root:file:/root/.ssh/lab_rsa.pub" --selinux-relabel --run-command 'yum remove cloud-init* -y'
    
# Destroy Existing Disk. If Available. 
- name: Destroy Helper Qcow2 
  ansible.builtin.file:
    path: "/var/lib/libvirt/images/{{helper_disk }}"
    state: absent
  tags:
    - virt
    
# Prepare the Helper Image 
- name: Create Helper VM Disk
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ rhel9_kvm_image }}"
    dest: "/var/lib/libvirt/images/{{ helper_disk }}"
  tags:
  - copy 
  - virt

- name: Setup the DHCP Network 
  shell: | 
    virsh net-update --network "default" add-last ip-dhcp-host \
    --xml "<host mac='52:54:00:e2:54:{{ item.value }}' ip='192.168.122.{{ item.value }}' />" --live --config
  with_dict:
  - "{{ ip_list }}"
  ignore_errors: yes
  
- name: Define the Helper VM 
  shell: |
    virt-install --import --name "{{ helper_name }}" --memory "{{ helper_memory }}" --vcpus "{{ helper_vcpus }}"  --disk "/var/lib/libvirt/images/{{ helper_disk }}",format=qcow2,bus=virtio  --os-variant=rhel9.4 --noautoconsole --network network:default,mac=52:54:00:e2:54:{{ip_list.helper_server}}
  tags:
  - virt

