---
# tasks file for roles/setup-bm-host
- name: Registering Hypervisor Node to Subscription Manager
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ org_id }}"

- name: Install Basic Required Packages.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - "{{ basic_packages }}"

