---
# Start with Installing the required packages on the Host

- name: Install Basic Required Packages.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
  - "{{ basic_packages }}"

# Once Packages are installed, lets start the Libvirt Service
- name: Start Libvirtd Service
  systemd:
    state: started
    name: libvirtd
    enabled: yes

# Create SSH KeyPair

- name: Create ssh KeyPair
  shell: |
    ssh-keygen -b 2048 -t rsa -f ~/.ssh/lab_rsa -q -N ""

# Setting Strict HostKey Checking False
#- name: Setting host key checking false for Ansible
#  lineinfile:
#    path: /etc/ansible/ansible.cfg
#    regexp: '^#host_key_checking'
#    insertafter: '^#host_key_checking'
#    line: host_key_checking = False

# Enable Nested KVM
- name: Enable Nested KVM
  copy:
    dest: /etc/modprobe.d/kvm-nested.conf
    content: |
      options kvm-intel nested=1


# Prepare the KVM Image 
- name: Remove Cloud-Init & Add Password  
  shell: | 
    virt-customize -a ./files/{{ rhel9_kvm_image }} --root-password password:redhat --ssh-inject "root:file:/root/.ssh/id_rsa.pub" --selinux-relabel --run-command 'yum remove cloud-init* -y'
