- name: Setting Up Hub Cluster
  hosts: localhost
  become: true
  vars_files:
    - vars.yaml
    - vault.yaml 
  tasks: 
  - ansible.builtin.import_role:
      name: setup-hub-cluster

  - ansible.builtin.import_role:
      name: setup-hub-acm
    environment:
      KUBECONFIG: "{{ hub_install_folder }}/auth/kubeconfig"
    tags:
      - acm    
