---
# tasks file for setup-gitops
# Create the Namespace
- name: Check Namespace
  shell: oc get projects | grep openshift-gitops-operator
  ignore_errors: yes
  register: projects_out

- name: Create Namespace
  shell: oc create ns openshift-gitops-operator
  when: "'Active' not in projects_out.stdout"

- name: Check OG
  shell: oc get og -A | grep openshift-gitops-operator
  ignore_errors: yes
  register: og_out

- name: Create OperatorGroup
  shell: oc create -f "{{ role_path }}/files/operatorGroup.yaml"
  when: "'openshift-gitops-operator' not in og_out.stdout"

- name: Check Subs
  shell: oc get subscriptions -A | grep openshift-gitops-operator
  ignore_errors: yes
  register: sub_out

- name: Create Subscription for Openshift-Gitops 
  shell: oc create -f "{{ role_path }}/files/subscription.yaml"
  when: "'openshift-gitops-operator' not in sub_out.stdout"

- name: Lets wait for 200 seconds for the workers to be UP and RUNNING. 
  ansible.builtin.wait_for:
    timeout: 200

- name: Allow openshift-gitops to deploy in open-cluster-management
  shell: oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller 

- name: Define App of Apps
  shell: oc create -f "{{ role_path }}/files/app-of-apps.yaml"

