apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: my-lvmcluster
spec:
  storage:
    deviceClasses:
    - name: vg1
      fstype: ext4 
      default: true
      nodeSelector: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: storage
            operator: In
            values:
            - true
      deviceSelector: 
        paths:
        - vdb 
        forceWipeDevicesAndDestroyAllData: true
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90 
        overprovisionRatio: 10
        chunkSize: 128Ki 
        chunkSizeCalculationPolicy: Static 
