apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: default-acm
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
