---
# tasks file for setup-hub-acm
- name: Setup ACM 
  shell: |
    oc apply -f "{{ role_path }}/files/acm/01-namespace.yaml"
    oc apply -f "{{ role_path }}/files/acm/02-acm-operatorgroup.yaml"
    oc apply -f "{{ role_path }}/files/acm/03-subscription.yaml"
    sleep 180s
    oc apply -f "{{ role_path }}/files/acm/04-multicluster-hub.yaml"

- name: Setup LVM Storage
  shell: |
    oc apply -f "{{ role_path }}/files/lvm-storage/01-namespace.yaml"
    oc apply -f "{{ role_path }}/files/lvm-storage/02-operatorGroup.yaml"
    oc apply -f "{{ role_path }}/files/lvm-storage/03-subscription.yaml"
    sleep 180s
    oc apply -f "{{ role_path }}/files/lvm-storage/04-lvm-cluster.yaml"


- name: Setup MetalLB 
  shell: |
    oc apply -f "{{ role_path }}/files/metal-lb/01-namespace.yaml"
    oc apply -f "{{ role_path }}/files/metal-lb/02-operatorGroup.yaml"
    oc apply -f "{{ role_path }}/files/metal-lb/03-subscription.yaml"
    sleep 180s
    oc apply -f "{{ role_path }}/files/metal-lb/04-metalLB.yaml"
    oc apply -f "{{ role_path }}/files/metal-lb/05-ip-pool.yaml"
    oc apply -f "{{ role_path }}/files/metal-lb/06-L2Advertisement.yaml"


